project:
  type: website

website:
  title: "My Quarto Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: walkthrough.qmd
        text: Walkthrough

format:
  html:
    theme: cosmo
    toc: true
